/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminVotingFaqsRouteImport } from './routes/admin.voting-faqs'
import { Route as AdminSittingMpsRouteImport } from './routes/admin.sitting-mps'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminProposalsRouteImport } from './routes/admin.proposals'
import { Route as AdminPartiesRouteImport } from './routes/admin.parties'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminDuplicatesRouteImport } from './routes/admin.duplicates'
import { Route as AdminDistrictsRouteImport } from './routes/admin.districts'
import { Route as AdminCustomFieldsRouteImport } from './routes/admin.custom-fields'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApiLogsRouteImport } from './routes/admin.api-logs'
import { Route as LangTermsRouteImport } from './routes/$lang.terms'
import { Route as LangSittingMpsRouteImport } from './routes/$lang.sitting-mps'
import { Route as LangSearchRouteImport } from './routes/$lang.search'
import { Route as LangResourcesRouteImport } from './routes/$lang.resources'
import { Route as LangProposalsRouteImport } from './routes/$lang.proposals'
import { Route as LangPrivacyRouteImport } from './routes/$lang.privacy'
import { Route as LangFaqRouteImport } from './routes/$lang.faq'
import { Route as LangDistrictsRouteImport } from './routes/$lang.districts'
import { Route as LangDevelopersRouteImport } from './routes/$lang.developers'
import { Route as LangCookiesRouteImport } from './routes/$lang.cookies'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangCompareRouteImport } from './routes/$lang.compare'
import { Route as LangChangelogRouteImport } from './routes/$lang.changelog'
import { Route as LangAskRouteImport } from './routes/$lang.ask'
import { Route as LangAccessibilityRouteImport } from './routes/$lang.accessibility'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangPartiesIndexRouteImport } from './routes/$lang.parties.index'
import { Route as LangCandidatesIndexRouteImport } from './routes/$lang.candidates.index'
import { Route as LangPartiesSlugRouteImport } from './routes/$lang.parties.$slug'
import { Route as LangMyDistrictNumberRouteImport } from './routes/$lang.my-district.$number'
import { Route as LangCandidatesSlugRouteImport } from './routes/$lang.candidates.$slug'
import { Route as ApiPublicV1PartiesRouteImport } from './routes/api/public/v1/parties'
import { Route as ApiPublicV1DistrictsRouteImport } from './routes/api/public/v1/districts'
import { Route as ApiPublicV1CandidatesRouteImport } from './routes/api/public/v1/candidates'
import { Route as ApiPublicHooksScanNewsRouteImport } from './routes/api/public/hooks/scan-news'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVotingFaqsRoute = AdminVotingFaqsRouteImport.update({
  id: '/voting-faqs',
  path: '/voting-faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSittingMpsRoute = AdminSittingMpsRouteImport.update({
  id: '/sitting-mps',
  path: '/sitting-mps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProposalsRoute = AdminProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartiesRoute = AdminPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDuplicatesRoute = AdminDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistrictsRoute = AdminDistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomFieldsRoute = AdminCustomFieldsRouteImport.update({
  id: '/custom-fields',
  path: '/custom-fields',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiLogsRoute = AdminApiLogsRouteImport.update({
  id: '/api-logs',
  path: '/api-logs',
  getParentRoute: () => AdminRoute,
} as any)
const LangTermsRoute = LangTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LangRoute,
} as any)
const LangSittingMpsRoute = LangSittingMpsRouteImport.update({
  id: '/sitting-mps',
  path: '/sitting-mps',
  getParentRoute: () => LangRoute,
} as any)
const LangSearchRoute = LangSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LangRoute,
} as any)
const LangResourcesRoute = LangResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => LangRoute,
} as any)
const LangProposalsRoute = LangProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRoute,
} as any)
const LangFaqRoute = LangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LangRoute,
} as any)
const LangDistrictsRoute = LangDistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => LangRoute,
} as any)
const LangDevelopersRoute = LangDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => LangRoute,
} as any)
const LangCookiesRoute = LangCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangCompareRoute = LangCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LangRoute,
} as any)
const LangChangelogRoute = LangChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LangRoute,
} as any)
const LangAskRoute = LangAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => LangRoute,
} as any)
const LangAccessibilityRoute = LangAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangPartiesIndexRoute = LangPartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => LangRoute,
} as any)
const LangCandidatesIndexRoute = LangCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => LangRoute,
} as any)
const LangPartiesSlugRoute = LangPartiesSlugRouteImport.update({
  id: '/parties/$slug',
  path: '/parties/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangMyDistrictNumberRoute = LangMyDistrictNumberRouteImport.update({
  id: '/my-district/$number',
  path: '/my-district/$number',
  getParentRoute: () => LangRoute,
} as any)
const LangCandidatesSlugRoute = LangCandidatesSlugRouteImport.update({
  id: '/candidates/$slug',
  path: '/candidates/$slug',
  getParentRoute: () => LangRoute,
} as any)
const ApiPublicV1PartiesRoute = ApiPublicV1PartiesRouteImport.update({
  id: '/api/public/v1/parties',
  path: '/api/public/v1/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DistrictsRoute = ApiPublicV1DistrictsRouteImport.update({
  id: '/api/public/v1/districts',
  path: '/api/public/v1/districts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CandidatesRoute = ApiPublicV1CandidatesRouteImport.update({
  id: '/api/public/v1/candidates',
  path: '/api/public/v1/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScanNewsRoute = ApiPublicHooksScanNewsRouteImport.update({
  id: '/api/public/hooks/scan-news',
  path: '/api/public/hooks/scan-news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/accessibility': typeof LangAccessibilityRoute
  '/$lang/ask': typeof LangAskRoute
  '/$lang/changelog': typeof LangChangelogRoute
  '/$lang/compare': typeof LangCompareRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/developers': typeof LangDevelopersRoute
  '/$lang/districts': typeof LangDistrictsRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/proposals': typeof LangProposalsRoute
  '/$lang/resources': typeof LangResourcesRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/sitting-mps': typeof LangSittingMpsRoute
  '/$lang/terms': typeof LangTermsRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/custom-fields': typeof AdminCustomFieldsRoute
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/parties': typeof AdminPartiesRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sitting-mps': typeof AdminSittingMpsRoute
  '/admin/voting-faqs': typeof AdminVotingFaqsRoute
  '/auth/login': typeof AuthLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/candidates/$slug': typeof LangCandidatesSlugRoute
  '/$lang/my-district/$number': typeof LangMyDistrictNumberRoute
  '/$lang/parties/$slug': typeof LangPartiesSlugRoute
  '/$lang/candidates/': typeof LangCandidatesIndexRoute
  '/$lang/parties/': typeof LangPartiesIndexRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/v1/candidates': typeof ApiPublicV1CandidatesRoute
  '/api/public/v1/districts': typeof ApiPublicV1DistrictsRoute
  '/api/public/v1/parties': typeof ApiPublicV1PartiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/accessibility': typeof LangAccessibilityRoute
  '/$lang/ask': typeof LangAskRoute
  '/$lang/changelog': typeof LangChangelogRoute
  '/$lang/compare': typeof LangCompareRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/developers': typeof LangDevelopersRoute
  '/$lang/districts': typeof LangDistrictsRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/proposals': typeof LangProposalsRoute
  '/$lang/resources': typeof LangResourcesRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/sitting-mps': typeof LangSittingMpsRoute
  '/$lang/terms': typeof LangTermsRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/custom-fields': typeof AdminCustomFieldsRoute
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/parties': typeof AdminPartiesRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sitting-mps': typeof AdminSittingMpsRoute
  '/admin/voting-faqs': typeof AdminVotingFaqsRoute
  '/auth/login': typeof AuthLoginRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$lang/candidates/$slug': typeof LangCandidatesSlugRoute
  '/$lang/my-district/$number': typeof LangMyDistrictNumberRoute
  '/$lang/parties/$slug': typeof LangPartiesSlugRoute
  '/$lang/candidates': typeof LangCandidatesIndexRoute
  '/$lang/parties': typeof LangPartiesIndexRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/v1/candidates': typeof ApiPublicV1CandidatesRoute
  '/api/public/v1/districts': typeof ApiPublicV1DistrictsRoute
  '/api/public/v1/parties': typeof ApiPublicV1PartiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/accessibility': typeof LangAccessibilityRoute
  '/$lang/ask': typeof LangAskRoute
  '/$lang/changelog': typeof LangChangelogRoute
  '/$lang/compare': typeof LangCompareRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/developers': typeof LangDevelopersRoute
  '/$lang/districts': typeof LangDistrictsRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/proposals': typeof LangProposalsRoute
  '/$lang/resources': typeof LangResourcesRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/sitting-mps': typeof LangSittingMpsRoute
  '/$lang/terms': typeof LangTermsRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/custom-fields': typeof AdminCustomFieldsRoute
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/parties': typeof AdminPartiesRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sitting-mps': typeof AdminSittingMpsRoute
  '/admin/voting-faqs': typeof AdminVotingFaqsRoute
  '/auth/login': typeof AuthLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/candidates/$slug': typeof LangCandidatesSlugRoute
  '/$lang/my-district/$number': typeof LangMyDistrictNumberRoute
  '/$lang/parties/$slug': typeof LangPartiesSlugRoute
  '/$lang/candidates/': typeof LangCandidatesIndexRoute
  '/$lang/parties/': typeof LangPartiesIndexRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/v1/candidates': typeof ApiPublicV1CandidatesRoute
  '/api/public/v1/districts': typeof ApiPublicV1DistrictsRoute
  '/api/public/v1/parties': typeof ApiPublicV1PartiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/admin'
    | '/$lang/about'
    | '/$lang/accessibility'
    | '/$lang/ask'
    | '/$lang/changelog'
    | '/$lang/compare'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/developers'
    | '/$lang/districts'
    | '/$lang/faq'
    | '/$lang/privacy'
    | '/$lang/proposals'
    | '/$lang/resources'
    | '/$lang/search'
    | '/$lang/sitting-mps'
    | '/$lang/terms'
    | '/admin/api-logs'
    | '/admin/audit'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/custom-fields'
    | '/admin/districts'
    | '/admin/duplicates'
    | '/admin/news'
    | '/admin/parties'
    | '/admin/proposals'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/sitting-mps'
    | '/admin/voting-faqs'
    | '/auth/login'
    | '/$lang/'
    | '/admin/'
    | '/$lang/candidates/$slug'
    | '/$lang/my-district/$number'
    | '/$lang/parties/$slug'
    | '/$lang/candidates/'
    | '/$lang/parties/'
    | '/api/public/hooks/scan-news'
    | '/api/public/v1/candidates'
    | '/api/public/v1/districts'
    | '/api/public/v1/parties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/accessibility'
    | '/$lang/ask'
    | '/$lang/changelog'
    | '/$lang/compare'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/developers'
    | '/$lang/districts'
    | '/$lang/faq'
    | '/$lang/privacy'
    | '/$lang/proposals'
    | '/$lang/resources'
    | '/$lang/search'
    | '/$lang/sitting-mps'
    | '/$lang/terms'
    | '/admin/api-logs'
    | '/admin/audit'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/custom-fields'
    | '/admin/districts'
    | '/admin/duplicates'
    | '/admin/news'
    | '/admin/parties'
    | '/admin/proposals'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/sitting-mps'
    | '/admin/voting-faqs'
    | '/auth/login'
    | '/$lang'
    | '/admin'
    | '/$lang/candidates/$slug'
    | '/$lang/my-district/$number'
    | '/$lang/parties/$slug'
    | '/$lang/candidates'
    | '/$lang/parties'
    | '/api/public/hooks/scan-news'
    | '/api/public/v1/candidates'
    | '/api/public/v1/districts'
    | '/api/public/v1/parties'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/admin'
    | '/$lang/about'
    | '/$lang/accessibility'
    | '/$lang/ask'
    | '/$lang/changelog'
    | '/$lang/compare'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/developers'
    | '/$lang/districts'
    | '/$lang/faq'
    | '/$lang/privacy'
    | '/$lang/proposals'
    | '/$lang/resources'
    | '/$lang/search'
    | '/$lang/sitting-mps'
    | '/$lang/terms'
    | '/admin/api-logs'
    | '/admin/audit'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/custom-fields'
    | '/admin/districts'
    | '/admin/duplicates'
    | '/admin/news'
    | '/admin/parties'
    | '/admin/proposals'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/sitting-mps'
    | '/admin/voting-faqs'
    | '/auth/login'
    | '/$lang/'
    | '/admin/'
    | '/$lang/candidates/$slug'
    | '/$lang/my-district/$number'
    | '/$lang/parties/$slug'
    | '/$lang/candidates/'
    | '/$lang/parties/'
    | '/api/public/hooks/scan-news'
    | '/api/public/v1/candidates'
    | '/api/public/v1/districts'
    | '/api/public/v1/parties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  ApiPublicHooksScanNewsRoute: typeof ApiPublicHooksScanNewsRoute
  ApiPublicV1CandidatesRoute: typeof ApiPublicV1CandidatesRoute
  ApiPublicV1DistrictsRoute: typeof ApiPublicV1DistrictsRoute
  ApiPublicV1PartiesRoute: typeof ApiPublicV1PartiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voting-faqs': {
      id: '/admin/voting-faqs'
      path: '/voting-faqs'
      fullPath: '/admin/voting-faqs'
      preLoaderRoute: typeof AdminVotingFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sitting-mps': {
      id: '/admin/sitting-mps'
      path: '/sitting-mps'
      fullPath: '/admin/sitting-mps'
      preLoaderRoute: typeof AdminSittingMpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proposals': {
      id: '/admin/proposals'
      path: '/proposals'
      fullPath: '/admin/proposals'
      preLoaderRoute: typeof AdminProposalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parties': {
      id: '/admin/parties'
      path: '/parties'
      fullPath: '/admin/parties'
      preLoaderRoute: typeof AdminPartiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/duplicates': {
      id: '/admin/duplicates'
      path: '/duplicates'
      fullPath: '/admin/duplicates'
      preLoaderRoute: typeof AdminDuplicatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/districts': {
      id: '/admin/districts'
      path: '/districts'
      fullPath: '/admin/districts'
      preLoaderRoute: typeof AdminDistrictsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/custom-fields': {
      id: '/admin/custom-fields'
      path: '/custom-fields'
      fullPath: '/admin/custom-fields'
      preLoaderRoute: typeof AdminCustomFieldsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-logs': {
      id: '/admin/api-logs'
      path: '/api-logs'
      fullPath: '/admin/api-logs'
      preLoaderRoute: typeof AdminApiLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/terms': {
      id: '/$lang/terms'
      path: '/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangTermsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/sitting-mps': {
      id: '/$lang/sitting-mps'
      path: '/sitting-mps'
      fullPath: '/$lang/sitting-mps'
      preLoaderRoute: typeof LangSittingMpsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/search': {
      id: '/$lang/search'
      path: '/search'
      fullPath: '/$lang/search'
      preLoaderRoute: typeof LangSearchRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/resources': {
      id: '/$lang/resources'
      path: '/resources'
      fullPath: '/$lang/resources'
      preLoaderRoute: typeof LangResourcesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/proposals': {
      id: '/$lang/proposals'
      path: '/proposals'
      fullPath: '/$lang/proposals'
      preLoaderRoute: typeof LangProposalsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/faq': {
      id: '/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof LangFaqRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/districts': {
      id: '/$lang/districts'
      path: '/districts'
      fullPath: '/$lang/districts'
      preLoaderRoute: typeof LangDistrictsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/developers': {
      id: '/$lang/developers'
      path: '/developers'
      fullPath: '/$lang/developers'
      preLoaderRoute: typeof LangDevelopersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/cookies': {
      id: '/$lang/cookies'
      path: '/cookies'
      fullPath: '/$lang/cookies'
      preLoaderRoute: typeof LangCookiesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/compare': {
      id: '/$lang/compare'
      path: '/compare'
      fullPath: '/$lang/compare'
      preLoaderRoute: typeof LangCompareRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/changelog': {
      id: '/$lang/changelog'
      path: '/changelog'
      fullPath: '/$lang/changelog'
      preLoaderRoute: typeof LangChangelogRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/ask': {
      id: '/$lang/ask'
      path: '/ask'
      fullPath: '/$lang/ask'
      preLoaderRoute: typeof LangAskRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/accessibility': {
      id: '/$lang/accessibility'
      path: '/accessibility'
      fullPath: '/$lang/accessibility'
      preLoaderRoute: typeof LangAccessibilityRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/parties/': {
      id: '/$lang/parties/'
      path: '/parties'
      fullPath: '/$lang/parties/'
      preLoaderRoute: typeof LangPartiesIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/candidates/': {
      id: '/$lang/candidates/'
      path: '/candidates'
      fullPath: '/$lang/candidates/'
      preLoaderRoute: typeof LangCandidatesIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/parties/$slug': {
      id: '/$lang/parties/$slug'
      path: '/parties/$slug'
      fullPath: '/$lang/parties/$slug'
      preLoaderRoute: typeof LangPartiesSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/my-district/$number': {
      id: '/$lang/my-district/$number'
      path: '/my-district/$number'
      fullPath: '/$lang/my-district/$number'
      preLoaderRoute: typeof LangMyDistrictNumberRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/candidates/$slug': {
      id: '/$lang/candidates/$slug'
      path: '/candidates/$slug'
      fullPath: '/$lang/candidates/$slug'
      preLoaderRoute: typeof LangCandidatesSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/public/v1/parties': {
      id: '/api/public/v1/parties'
      path: '/api/public/v1/parties'
      fullPath: '/api/public/v1/parties'
      preLoaderRoute: typeof ApiPublicV1PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/districts': {
      id: '/api/public/v1/districts'
      path: '/api/public/v1/districts'
      fullPath: '/api/public/v1/districts'
      preLoaderRoute: typeof ApiPublicV1DistrictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/candidates': {
      id: '/api/public/v1/candidates'
      path: '/api/public/v1/candidates'
      fullPath: '/api/public/v1/candidates'
      preLoaderRoute: typeof ApiPublicV1CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-news': {
      id: '/api/public/hooks/scan-news'
      path: '/api/public/hooks/scan-news'
      fullPath: '/api/public/hooks/scan-news'
      preLoaderRoute: typeof ApiPublicHooksScanNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangAccessibilityRoute: typeof LangAccessibilityRoute
  LangAskRoute: typeof LangAskRoute
  LangChangelogRoute: typeof LangChangelogRoute
  LangCompareRoute: typeof LangCompareRoute
  LangContactRoute: typeof LangContactRoute
  LangCookiesRoute: typeof LangCookiesRoute
  LangDevelopersRoute: typeof LangDevelopersRoute
  LangDistrictsRoute: typeof LangDistrictsRoute
  LangFaqRoute: typeof LangFaqRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangProposalsRoute: typeof LangProposalsRoute
  LangResourcesRoute: typeof LangResourcesRoute
  LangSearchRoute: typeof LangSearchRoute
  LangSittingMpsRoute: typeof LangSittingMpsRoute
  LangTermsRoute: typeof LangTermsRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCandidatesSlugRoute: typeof LangCandidatesSlugRoute
  LangMyDistrictNumberRoute: typeof LangMyDistrictNumberRoute
  LangPartiesSlugRoute: typeof LangPartiesSlugRoute
  LangCandidatesIndexRoute: typeof LangCandidatesIndexRoute
  LangPartiesIndexRoute: typeof LangPartiesIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangAccessibilityRoute: LangAccessibilityRoute,
  LangAskRoute: LangAskRoute,
  LangChangelogRoute: LangChangelogRoute,
  LangCompareRoute: LangCompareRoute,
  LangContactRoute: LangContactRoute,
  LangCookiesRoute: LangCookiesRoute,
  LangDevelopersRoute: LangDevelopersRoute,
  LangDistrictsRoute: LangDistrictsRoute,
  LangFaqRoute: LangFaqRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangProposalsRoute: LangProposalsRoute,
  LangResourcesRoute: LangResourcesRoute,
  LangSearchRoute: LangSearchRoute,
  LangSittingMpsRoute: LangSittingMpsRoute,
  LangTermsRoute: LangTermsRoute,
  LangIndexRoute: LangIndexRoute,
  LangCandidatesSlugRoute: LangCandidatesSlugRoute,
  LangMyDistrictNumberRoute: LangMyDistrictNumberRoute,
  LangPartiesSlugRoute: LangPartiesSlugRoute,
  LangCandidatesIndexRoute: LangCandidatesIndexRoute,
  LangPartiesIndexRoute: LangPartiesIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminRouteChildren {
  AdminApiLogsRoute: typeof AdminApiLogsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomFieldsRoute: typeof AdminCustomFieldsRoute
  AdminDistrictsRoute: typeof AdminDistrictsRoute
  AdminDuplicatesRoute: typeof AdminDuplicatesRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPartiesRoute: typeof AdminPartiesRoute
  AdminProposalsRoute: typeof AdminProposalsRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSittingMpsRoute: typeof AdminSittingMpsRoute
  AdminVotingFaqsRoute: typeof AdminVotingFaqsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiLogsRoute: AdminApiLogsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomFieldsRoute: AdminCustomFieldsRoute,
  AdminDistrictsRoute: AdminDistrictsRoute,
  AdminDuplicatesRoute: AdminDuplicatesRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPartiesRoute: AdminPartiesRoute,
  AdminProposalsRoute: AdminProposalsRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSittingMpsRoute: AdminSittingMpsRoute,
  AdminVotingFaqsRoute: AdminVotingFaqsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  ApiPublicHooksScanNewsRoute: ApiPublicHooksScanNewsRoute,
  ApiPublicV1CandidatesRoute: ApiPublicV1CandidatesRoute,
  ApiPublicV1DistrictsRoute: ApiPublicV1DistrictsRoute,
  ApiPublicV1PartiesRoute: ApiPublicV1PartiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
