/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as LangTermsRouteImport } from './routes/$lang.terms'
import { Route as LangSittingMpsRouteImport } from './routes/$lang.sitting-mps'
import { Route as LangPrivacyRouteImport } from './routes/$lang.privacy'
import { Route as LangPartiesRouteImport } from './routes/$lang.parties'
import { Route as LangDistrictsRouteImport } from './routes/$lang.districts'
import { Route as LangDevelopersRouteImport } from './routes/$lang.developers'
import { Route as LangCookiesRouteImport } from './routes/$lang.cookies'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangCompareRouteImport } from './routes/$lang.compare'
import { Route as LangChangelogRouteImport } from './routes/$lang.changelog'
import { Route as LangAskRouteImport } from './routes/$lang.ask'
import { Route as LangAccessibilityRouteImport } from './routes/$lang.accessibility'
import { Route as LangAboutRouteImport } from './routes/$lang.about'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTermsRoute = LangTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LangRoute,
} as any)
const LangSittingMpsRoute = LangSittingMpsRouteImport.update({
  id: '/sitting-mps',
  path: '/sitting-mps',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRoute,
} as any)
const LangPartiesRoute = LangPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => LangRoute,
} as any)
const LangDistrictsRoute = LangDistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => LangRoute,
} as any)
const LangDevelopersRoute = LangDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => LangRoute,
} as any)
const LangCookiesRoute = LangCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangCompareRoute = LangCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LangRoute,
} as any)
const LangChangelogRoute = LangChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LangRoute,
} as any)
const LangAskRoute = LangAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => LangRoute,
} as any)
const LangAccessibilityRoute = LangAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/accessibility': typeof LangAccessibilityRoute
  '/$lang/ask': typeof LangAskRoute
  '/$lang/changelog': typeof LangChangelogRoute
  '/$lang/compare': typeof LangCompareRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/developers': typeof LangDevelopersRoute
  '/$lang/districts': typeof LangDistrictsRoute
  '/$lang/parties': typeof LangPartiesRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/sitting-mps': typeof LangSittingMpsRoute
  '/$lang/terms': typeof LangTermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/accessibility': typeof LangAccessibilityRoute
  '/$lang/ask': typeof LangAskRoute
  '/$lang/changelog': typeof LangChangelogRoute
  '/$lang/compare': typeof LangCompareRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/developers': typeof LangDevelopersRoute
  '/$lang/districts': typeof LangDistrictsRoute
  '/$lang/parties': typeof LangPartiesRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/sitting-mps': typeof LangSittingMpsRoute
  '/$lang/terms': typeof LangTermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/accessibility': typeof LangAccessibilityRoute
  '/$lang/ask': typeof LangAskRoute
  '/$lang/changelog': typeof LangChangelogRoute
  '/$lang/compare': typeof LangCompareRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/developers': typeof LangDevelopersRoute
  '/$lang/districts': typeof LangDistrictsRoute
  '/$lang/parties': typeof LangPartiesRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/sitting-mps': typeof LangSittingMpsRoute
  '/$lang/terms': typeof LangTermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/admin'
    | '/$lang/about'
    | '/$lang/accessibility'
    | '/$lang/ask'
    | '/$lang/changelog'
    | '/$lang/compare'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/developers'
    | '/$lang/districts'
    | '/$lang/parties'
    | '/$lang/privacy'
    | '/$lang/sitting-mps'
    | '/$lang/terms'
    | '/auth/login'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/$lang/about'
    | '/$lang/accessibility'
    | '/$lang/ask'
    | '/$lang/changelog'
    | '/$lang/compare'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/developers'
    | '/$lang/districts'
    | '/$lang/parties'
    | '/$lang/privacy'
    | '/$lang/sitting-mps'
    | '/$lang/terms'
    | '/auth/login'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/admin'
    | '/$lang/about'
    | '/$lang/accessibility'
    | '/$lang/ask'
    | '/$lang/changelog'
    | '/$lang/compare'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/developers'
    | '/$lang/districts'
    | '/$lang/parties'
    | '/$lang/privacy'
    | '/$lang/sitting-mps'
    | '/$lang/terms'
    | '/auth/login'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/terms': {
      id: '/$lang/terms'
      path: '/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangTermsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/sitting-mps': {
      id: '/$lang/sitting-mps'
      path: '/sitting-mps'
      fullPath: '/$lang/sitting-mps'
      preLoaderRoute: typeof LangSittingMpsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/parties': {
      id: '/$lang/parties'
      path: '/parties'
      fullPath: '/$lang/parties'
      preLoaderRoute: typeof LangPartiesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/districts': {
      id: '/$lang/districts'
      path: '/districts'
      fullPath: '/$lang/districts'
      preLoaderRoute: typeof LangDistrictsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/developers': {
      id: '/$lang/developers'
      path: '/developers'
      fullPath: '/$lang/developers'
      preLoaderRoute: typeof LangDevelopersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/cookies': {
      id: '/$lang/cookies'
      path: '/cookies'
      fullPath: '/$lang/cookies'
      preLoaderRoute: typeof LangCookiesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/compare': {
      id: '/$lang/compare'
      path: '/compare'
      fullPath: '/$lang/compare'
      preLoaderRoute: typeof LangCompareRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/changelog': {
      id: '/$lang/changelog'
      path: '/changelog'
      fullPath: '/$lang/changelog'
      preLoaderRoute: typeof LangChangelogRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/ask': {
      id: '/$lang/ask'
      path: '/ask'
      fullPath: '/$lang/ask'
      preLoaderRoute: typeof LangAskRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/accessibility': {
      id: '/$lang/accessibility'
      path: '/accessibility'
      fullPath: '/$lang/accessibility'
      preLoaderRoute: typeof LangAccessibilityRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangAccessibilityRoute: typeof LangAccessibilityRoute
  LangAskRoute: typeof LangAskRoute
  LangChangelogRoute: typeof LangChangelogRoute
  LangCompareRoute: typeof LangCompareRoute
  LangContactRoute: typeof LangContactRoute
  LangCookiesRoute: typeof LangCookiesRoute
  LangDevelopersRoute: typeof LangDevelopersRoute
  LangDistrictsRoute: typeof LangDistrictsRoute
  LangPartiesRoute: typeof LangPartiesRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangSittingMpsRoute: typeof LangSittingMpsRoute
  LangTermsRoute: typeof LangTermsRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangAccessibilityRoute: LangAccessibilityRoute,
  LangAskRoute: LangAskRoute,
  LangChangelogRoute: LangChangelogRoute,
  LangCompareRoute: LangCompareRoute,
  LangContactRoute: LangContactRoute,
  LangCookiesRoute: LangCookiesRoute,
  LangDevelopersRoute: LangDevelopersRoute,
  LangDistrictsRoute: LangDistrictsRoute,
  LangPartiesRoute: LangPartiesRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangSittingMpsRoute: LangSittingMpsRoute,
  LangTermsRoute: LangTermsRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
