/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminVotingFaqsRouteImport } from './routes/admin.voting-faqs'
import { Route as AdminTranslationsRouteImport } from './routes/admin.translations'
import { Route as AdminSittingMpsRouteImport } from './routes/admin.sitting-mps'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminProposalsRouteImport } from './routes/admin.proposals'
import { Route as AdminPartiesRouteImport } from './routes/admin.parties'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminManifestoImportsRouteImport } from './routes/admin.manifesto-imports'
import { Route as AdminDuplicatesRouteImport } from './routes/admin.duplicates'
import { Route as AdminDistrictsRouteImport } from './routes/admin.districts'
import { Route as AdminDisclaimersRouteImport } from './routes/admin.disclaimers'
import { Route as AdminCustomFieldsRouteImport } from './routes/admin.custom-fields'
import { Route as AdminCommunityProposalsRouteImport } from './routes/admin.community-proposals'
import { Route as AdminCommunityAuthorsRouteImport } from './routes/admin.community-authors'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminCandidateSuggestionsRouteImport } from './routes/admin.candidate-suggestions'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAssistantRouteImport } from './routes/admin.assistant'
import { Route as AdminApiLogsRouteImport } from './routes/admin.api-logs'
import { Route as LangThemesRouteImport } from './routes/$lang.themes'
import { Route as LangTermsRouteImport } from './routes/$lang.terms'
import { Route as LangSupportersRouteImport } from './routes/$lang.supporters'
import { Route as LangSupportRouteImport } from './routes/$lang.support'
import { Route as LangSittingMpsRouteImport } from './routes/$lang.sitting-mps'
import { Route as LangSearchRouteImport } from './routes/$lang.search'
import { Route as LangResourcesRouteImport } from './routes/$lang.resources'
import { Route as LangProposalsRouteImport } from './routes/$lang.proposals'
import { Route as LangPrivacyRouteImport } from './routes/$lang.privacy'
import { Route as LangPartiesCompareRouteImport } from './routes/$lang.parties-compare'
import { Route as LangMethodologyRouteImport } from './routes/$lang.methodology'
import { Route as LangFaqRouteImport } from './routes/$lang.faq'
import { Route as LangDistrictsRouteImport } from './routes/$lang.districts'
import { Route as LangDevelopersRouteImport } from './routes/$lang.developers'
import { Route as LangDataRouteImport } from './routes/$lang.data'
import { Route as LangCookiesRouteImport } from './routes/$lang.cookies'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangCompareRouteImport } from './routes/$lang.compare'
import { Route as LangCommunityProposalsRouteImport } from './routes/$lang.community-proposals'
import { Route as LangChangelogRouteImport } from './routes/$lang.changelog'
import { Route as LangAskRouteImport } from './routes/$lang.ask'
import { Route as LangAccessibilityRouteImport } from './routes/$lang.accessibility'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangPartiesIndexRouteImport } from './routes/$lang.parties.index'
import { Route as LangCandidatesIndexRouteImport } from './routes/$lang.candidates.index'
import { Route as AdminCandidatesConfirmEcRouteImport } from './routes/admin.candidates_.confirm-ec'
import { Route as LangPartiesSlugRouteImport } from './routes/$lang.parties.$slug'
import { Route as LangMyDistrictNumberRouteImport } from './routes/$lang.my-district.$number'
import { Route as LangCandidatesSlugRouteImport } from './routes/$lang.candidates.$slug'
import { Route as ApiPublicV1PartiesRouteImport } from './routes/api/public/v1/parties'
import { Route as ApiPublicV1DistrictsRouteImport } from './routes/api/public/v1/districts'
import { Route as ApiPublicV1CatalogDotjsonldRouteImport } from './routes/api/public/v1/catalog[.]jsonld'
import { Route as ApiPublicV1CandidatesRouteImport } from './routes/api/public/v1/candidates'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksTelegramPollRouteImport } from './routes/api/public/hooks/telegram-poll'
import { Route as ApiPublicHooksScanNewsRouteImport } from './routes/api/public/hooks/scan-news'
import { Route as ApiPublicHooksManifestoTickRouteImport } from './routes/api/public/hooks/manifesto-tick'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVotingFaqsRoute = AdminVotingFaqsRouteImport.update({
  id: '/voting-faqs',
  path: '/voting-faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSittingMpsRoute = AdminSittingMpsRouteImport.update({
  id: '/sitting-mps',
  path: '/sitting-mps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProposalsRoute = AdminProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartiesRoute = AdminPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManifestoImportsRoute = AdminManifestoImportsRouteImport.update({
  id: '/manifesto-imports',
  path: '/manifesto-imports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDuplicatesRoute = AdminDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistrictsRoute = AdminDistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisclaimersRoute = AdminDisclaimersRouteImport.update({
  id: '/disclaimers',
  path: '/disclaimers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomFieldsRoute = AdminCustomFieldsRouteImport.update({
  id: '/custom-fields',
  path: '/custom-fields',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityProposalsRoute = AdminCommunityProposalsRouteImport.update({
  id: '/community-proposals',
  path: '/community-proposals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityAuthorsRoute = AdminCommunityAuthorsRouteImport.update({
  id: '/community-authors',
  path: '/community-authors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidateSuggestionsRoute =
  AdminCandidateSuggestionsRouteImport.update({
    id: '/candidate-suggestions',
    path: '/candidate-suggestions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssistantRoute = AdminAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiLogsRoute = AdminApiLogsRouteImport.update({
  id: '/api-logs',
  path: '/api-logs',
  getParentRoute: () => AdminRoute,
} as any)
const LangThemesRoute = LangThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => LangRoute,
} as any)
const LangTermsRoute = LangTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LangRoute,
} as any)
const LangSupportersRoute = LangSupportersRouteImport.update({
  id: '/supporters',
  path: '/supporters',
  getParentRoute: () => LangRoute,
} as any)
const LangSupportRoute = LangSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => LangRoute,
} as any)
const LangSittingMpsRoute = LangSittingMpsRouteImport.update({
  id: '/sitting-mps',
  path: '/sitting-mps',
  getParentRoute: () => LangRoute,
} as any)
const LangSearchRoute = LangSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LangRoute,
} as any)
const LangResourcesRoute = LangResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => LangRoute,
} as any)
const LangProposalsRoute = LangProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRoute,
} as any)
const LangPartiesCompareRoute = LangPartiesCompareRouteImport.update({
  id: '/parties-compare',
  path: '/parties-compare',
  getParentRoute: () => LangRoute,
} as any)
const LangMethodologyRoute = LangMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => LangRoute,
} as any)
const LangFaqRoute = LangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LangRoute,
} as any)
const LangDistrictsRoute = LangDistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => LangRoute,
} as any)
const LangDevelopersRoute = LangDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => LangRoute,
} as any)
const LangDataRoute = LangDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => LangRoute,
} as any)
const LangCookiesRoute = LangCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangCompareRoute = LangCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LangRoute,
} as any)
const LangCommunityProposalsRoute = LangCommunityProposalsRouteImport.update({
  id: '/community-proposals',
  path: '/community-proposals',
  getParentRoute: () => LangRoute,
} as any)
const LangChangelogRoute = LangChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LangRoute,
} as any)
const LangAskRoute = LangAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => LangRoute,
} as any)
const LangAccessibilityRoute = LangAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangPartiesIndexRoute = LangPartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => LangRoute,
} as any)
const LangCandidatesIndexRoute = LangCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => LangRoute,
} as any)
const AdminCandidatesConfirmEcRoute =
  AdminCandidatesConfirmEcRouteImport.update({
    id: '/candidates_/confirm-ec',
    path: '/candidates/confirm-ec',
    getParentRoute: () => AdminRoute,
  } as any)
const LangPartiesSlugRoute = LangPartiesSlugRouteImport.update({
  id: '/parties/$slug',
  path: '/parties/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangMyDistrictNumberRoute = LangMyDistrictNumberRouteImport.update({
  id: '/my-district/$number',
  path: '/my-district/$number',
  getParentRoute: () => LangRoute,
} as any)
const LangCandidatesSlugRoute = LangCandidatesSlugRouteImport.update({
  id: '/candidates/$slug',
  path: '/candidates/$slug',
  getParentRoute: () => LangRoute,
} as any)
const ApiPublicV1PartiesRoute = ApiPublicV1PartiesRouteImport.update({
  id: '/api/public/v1/parties',
  path: '/api/public/v1/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DistrictsRoute = ApiPublicV1DistrictsRouteImport.update({
  id: '/api/public/v1/districts',
  path: '/api/public/v1/districts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CatalogDotjsonldRoute =
  ApiPublicV1CatalogDotjsonldRouteImport.update({
    id: '/api/public/v1/catalog.jsonld',
    path: '/api/public/v1/catalog.jsonld',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1CandidatesRoute = ApiPublicV1CandidatesRouteImport.update({
  id: '/api/public/v1/candidates',
  path: '/api/public/v1/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramPollRoute =
  ApiPublicHooksTelegramPollRouteImport.update({
    id: '/api/public/hooks/telegram-poll',
    path: '/api/public/hooks/telegram-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScanNewsRoute = ApiPublicHooksScanNewsRouteImport.update({
  id: '/api/public/hooks/scan-news',
  path: '/api/public/hooks/scan-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksManifestoTickRoute =
  ApiPublicHooksManifestoTickRouteImport.update({
    id: '/api/public/hooks/manifesto-tick',
    path: '/api/public/hooks/manifesto-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/accessibility': typeof LangAccessibilityRoute
  '/$lang/ask': typeof LangAskRoute
  '/$lang/changelog': typeof LangChangelogRoute
  '/$lang/community-proposals': typeof LangCommunityProposalsRoute
  '/$lang/compare': typeof LangCompareRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/data': typeof LangDataRoute
  '/$lang/developers': typeof LangDevelopersRoute
  '/$lang/districts': typeof LangDistrictsRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/methodology': typeof LangMethodologyRoute
  '/$lang/parties-compare': typeof LangPartiesCompareRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/proposals': typeof LangProposalsRoute
  '/$lang/resources': typeof LangResourcesRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/sitting-mps': typeof LangSittingMpsRoute
  '/$lang/support': typeof LangSupportRoute
  '/$lang/supporters': typeof LangSupportersRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/themes': typeof LangThemesRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/candidate-suggestions': typeof AdminCandidateSuggestionsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/community-authors': typeof AdminCommunityAuthorsRoute
  '/admin/community-proposals': typeof AdminCommunityProposalsRoute
  '/admin/custom-fields': typeof AdminCustomFieldsRoute
  '/admin/disclaimers': typeof AdminDisclaimersRoute
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/manifesto-imports': typeof AdminManifestoImportsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/parties': typeof AdminPartiesRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sitting-mps': typeof AdminSittingMpsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/voting-faqs': typeof AdminVotingFaqsRoute
  '/auth/login': typeof AuthLoginRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/candidates/$slug': typeof LangCandidatesSlugRoute
  '/$lang/my-district/$number': typeof LangMyDistrictNumberRoute
  '/$lang/parties/$slug': typeof LangPartiesSlugRoute
  '/admin/candidates/confirm-ec': typeof AdminCandidatesConfirmEcRoute
  '/$lang/candidates/': typeof LangCandidatesIndexRoute
  '/$lang/parties/': typeof LangPartiesIndexRoute
  '/api/public/hooks/manifesto-tick': typeof ApiPublicHooksManifestoTickRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/hooks/telegram-poll': typeof ApiPublicHooksTelegramPollRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/candidates': typeof ApiPublicV1CandidatesRoute
  '/api/public/v1/catalog.jsonld': typeof ApiPublicV1CatalogDotjsonldRoute
  '/api/public/v1/districts': typeof ApiPublicV1DistrictsRoute
  '/api/public/v1/parties': typeof ApiPublicV1PartiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/accessibility': typeof LangAccessibilityRoute
  '/$lang/ask': typeof LangAskRoute
  '/$lang/changelog': typeof LangChangelogRoute
  '/$lang/community-proposals': typeof LangCommunityProposalsRoute
  '/$lang/compare': typeof LangCompareRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/data': typeof LangDataRoute
  '/$lang/developers': typeof LangDevelopersRoute
  '/$lang/districts': typeof LangDistrictsRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/methodology': typeof LangMethodologyRoute
  '/$lang/parties-compare': typeof LangPartiesCompareRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/proposals': typeof LangProposalsRoute
  '/$lang/resources': typeof LangResourcesRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/sitting-mps': typeof LangSittingMpsRoute
  '/$lang/support': typeof LangSupportRoute
  '/$lang/supporters': typeof LangSupportersRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/themes': typeof LangThemesRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/candidate-suggestions': typeof AdminCandidateSuggestionsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/community-authors': typeof AdminCommunityAuthorsRoute
  '/admin/community-proposals': typeof AdminCommunityProposalsRoute
  '/admin/custom-fields': typeof AdminCustomFieldsRoute
  '/admin/disclaimers': typeof AdminDisclaimersRoute
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/manifesto-imports': typeof AdminManifestoImportsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/parties': typeof AdminPartiesRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sitting-mps': typeof AdminSittingMpsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/voting-faqs': typeof AdminVotingFaqsRoute
  '/auth/login': typeof AuthLoginRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$lang/candidates/$slug': typeof LangCandidatesSlugRoute
  '/$lang/my-district/$number': typeof LangMyDistrictNumberRoute
  '/$lang/parties/$slug': typeof LangPartiesSlugRoute
  '/admin/candidates/confirm-ec': typeof AdminCandidatesConfirmEcRoute
  '/$lang/candidates': typeof LangCandidatesIndexRoute
  '/$lang/parties': typeof LangPartiesIndexRoute
  '/api/public/hooks/manifesto-tick': typeof ApiPublicHooksManifestoTickRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/hooks/telegram-poll': typeof ApiPublicHooksTelegramPollRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/candidates': typeof ApiPublicV1CandidatesRoute
  '/api/public/v1/catalog.jsonld': typeof ApiPublicV1CatalogDotjsonldRoute
  '/api/public/v1/districts': typeof ApiPublicV1DistrictsRoute
  '/api/public/v1/parties': typeof ApiPublicV1PartiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/accessibility': typeof LangAccessibilityRoute
  '/$lang/ask': typeof LangAskRoute
  '/$lang/changelog': typeof LangChangelogRoute
  '/$lang/community-proposals': typeof LangCommunityProposalsRoute
  '/$lang/compare': typeof LangCompareRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/data': typeof LangDataRoute
  '/$lang/developers': typeof LangDevelopersRoute
  '/$lang/districts': typeof LangDistrictsRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/methodology': typeof LangMethodologyRoute
  '/$lang/parties-compare': typeof LangPartiesCompareRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/proposals': typeof LangProposalsRoute
  '/$lang/resources': typeof LangResourcesRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/sitting-mps': typeof LangSittingMpsRoute
  '/$lang/support': typeof LangSupportRoute
  '/$lang/supporters': typeof LangSupportersRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/themes': typeof LangThemesRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/candidate-suggestions': typeof AdminCandidateSuggestionsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/community-authors': typeof AdminCommunityAuthorsRoute
  '/admin/community-proposals': typeof AdminCommunityProposalsRoute
  '/admin/custom-fields': typeof AdminCustomFieldsRoute
  '/admin/disclaimers': typeof AdminDisclaimersRoute
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/manifesto-imports': typeof AdminManifestoImportsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/parties': typeof AdminPartiesRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sitting-mps': typeof AdminSittingMpsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/voting-faqs': typeof AdminVotingFaqsRoute
  '/auth/login': typeof AuthLoginRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/candidates/$slug': typeof LangCandidatesSlugRoute
  '/$lang/my-district/$number': typeof LangMyDistrictNumberRoute
  '/$lang/parties/$slug': typeof LangPartiesSlugRoute
  '/admin/candidates_/confirm-ec': typeof AdminCandidatesConfirmEcRoute
  '/$lang/candidates/': typeof LangCandidatesIndexRoute
  '/$lang/parties/': typeof LangPartiesIndexRoute
  '/api/public/hooks/manifesto-tick': typeof ApiPublicHooksManifestoTickRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/hooks/telegram-poll': typeof ApiPublicHooksTelegramPollRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/candidates': typeof ApiPublicV1CandidatesRoute
  '/api/public/v1/catalog.jsonld': typeof ApiPublicV1CatalogDotjsonldRoute
  '/api/public/v1/districts': typeof ApiPublicV1DistrictsRoute
  '/api/public/v1/parties': typeof ApiPublicV1PartiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/admin'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/accessibility'
    | '/$lang/ask'
    | '/$lang/changelog'
    | '/$lang/community-proposals'
    | '/$lang/compare'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/data'
    | '/$lang/developers'
    | '/$lang/districts'
    | '/$lang/faq'
    | '/$lang/methodology'
    | '/$lang/parties-compare'
    | '/$lang/privacy'
    | '/$lang/proposals'
    | '/$lang/resources'
    | '/$lang/search'
    | '/$lang/sitting-mps'
    | '/$lang/support'
    | '/$lang/supporters'
    | '/$lang/terms'
    | '/$lang/themes'
    | '/admin/api-logs'
    | '/admin/assistant'
    | '/admin/audit'
    | '/admin/candidate-suggestions'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/community-authors'
    | '/admin/community-proposals'
    | '/admin/custom-fields'
    | '/admin/disclaimers'
    | '/admin/districts'
    | '/admin/duplicates'
    | '/admin/manifesto-imports'
    | '/admin/news'
    | '/admin/parties'
    | '/admin/proposals'
    | '/admin/resources'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/sitting-mps'
    | '/admin/translations'
    | '/admin/voting-faqs'
    | '/auth/login'
    | '/checkout/return'
    | '/$lang/'
    | '/admin/'
    | '/$lang/candidates/$slug'
    | '/$lang/my-district/$number'
    | '/$lang/parties/$slug'
    | '/admin/candidates/confirm-ec'
    | '/$lang/candidates/'
    | '/$lang/parties/'
    | '/api/public/hooks/manifesto-tick'
    | '/api/public/hooks/scan-news'
    | '/api/public/hooks/telegram-poll'
    | '/api/public/payments/webhook'
    | '/api/public/v1/candidates'
    | '/api/public/v1/catalog.jsonld'
    | '/api/public/v1/districts'
    | '/api/public/v1/parties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/accessibility'
    | '/$lang/ask'
    | '/$lang/changelog'
    | '/$lang/community-proposals'
    | '/$lang/compare'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/data'
    | '/$lang/developers'
    | '/$lang/districts'
    | '/$lang/faq'
    | '/$lang/methodology'
    | '/$lang/parties-compare'
    | '/$lang/privacy'
    | '/$lang/proposals'
    | '/$lang/resources'
    | '/$lang/search'
    | '/$lang/sitting-mps'
    | '/$lang/support'
    | '/$lang/supporters'
    | '/$lang/terms'
    | '/$lang/themes'
    | '/admin/api-logs'
    | '/admin/assistant'
    | '/admin/audit'
    | '/admin/candidate-suggestions'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/community-authors'
    | '/admin/community-proposals'
    | '/admin/custom-fields'
    | '/admin/disclaimers'
    | '/admin/districts'
    | '/admin/duplicates'
    | '/admin/manifesto-imports'
    | '/admin/news'
    | '/admin/parties'
    | '/admin/proposals'
    | '/admin/resources'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/sitting-mps'
    | '/admin/translations'
    | '/admin/voting-faqs'
    | '/auth/login'
    | '/checkout/return'
    | '/$lang'
    | '/admin'
    | '/$lang/candidates/$slug'
    | '/$lang/my-district/$number'
    | '/$lang/parties/$slug'
    | '/admin/candidates/confirm-ec'
    | '/$lang/candidates'
    | '/$lang/parties'
    | '/api/public/hooks/manifesto-tick'
    | '/api/public/hooks/scan-news'
    | '/api/public/hooks/telegram-poll'
    | '/api/public/payments/webhook'
    | '/api/public/v1/candidates'
    | '/api/public/v1/catalog.jsonld'
    | '/api/public/v1/districts'
    | '/api/public/v1/parties'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/admin'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/accessibility'
    | '/$lang/ask'
    | '/$lang/changelog'
    | '/$lang/community-proposals'
    | '/$lang/compare'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/data'
    | '/$lang/developers'
    | '/$lang/districts'
    | '/$lang/faq'
    | '/$lang/methodology'
    | '/$lang/parties-compare'
    | '/$lang/privacy'
    | '/$lang/proposals'
    | '/$lang/resources'
    | '/$lang/search'
    | '/$lang/sitting-mps'
    | '/$lang/support'
    | '/$lang/supporters'
    | '/$lang/terms'
    | '/$lang/themes'
    | '/admin/api-logs'
    | '/admin/assistant'
    | '/admin/audit'
    | '/admin/candidate-suggestions'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/community-authors'
    | '/admin/community-proposals'
    | '/admin/custom-fields'
    | '/admin/disclaimers'
    | '/admin/districts'
    | '/admin/duplicates'
    | '/admin/manifesto-imports'
    | '/admin/news'
    | '/admin/parties'
    | '/admin/proposals'
    | '/admin/resources'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/sitting-mps'
    | '/admin/translations'
    | '/admin/voting-faqs'
    | '/auth/login'
    | '/checkout/return'
    | '/$lang/'
    | '/admin/'
    | '/$lang/candidates/$slug'
    | '/$lang/my-district/$number'
    | '/$lang/parties/$slug'
    | '/admin/candidates_/confirm-ec'
    | '/$lang/candidates/'
    | '/$lang/parties/'
    | '/api/public/hooks/manifesto-tick'
    | '/api/public/hooks/scan-news'
    | '/api/public/hooks/telegram-poll'
    | '/api/public/payments/webhook'
    | '/api/public/v1/candidates'
    | '/api/public/v1/catalog.jsonld'
    | '/api/public/v1/districts'
    | '/api/public/v1/parties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthLoginRoute: typeof AuthLoginRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicHooksManifestoTickRoute: typeof ApiPublicHooksManifestoTickRoute
  ApiPublicHooksScanNewsRoute: typeof ApiPublicHooksScanNewsRoute
  ApiPublicHooksTelegramPollRoute: typeof ApiPublicHooksTelegramPollRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicV1CandidatesRoute: typeof ApiPublicV1CandidatesRoute
  ApiPublicV1CatalogDotjsonldRoute: typeof ApiPublicV1CatalogDotjsonldRoute
  ApiPublicV1DistrictsRoute: typeof ApiPublicV1DistrictsRoute
  ApiPublicV1PartiesRoute: typeof ApiPublicV1PartiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voting-faqs': {
      id: '/admin/voting-faqs'
      path: '/voting-faqs'
      fullPath: '/admin/voting-faqs'
      preLoaderRoute: typeof AdminVotingFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sitting-mps': {
      id: '/admin/sitting-mps'
      path: '/sitting-mps'
      fullPath: '/admin/sitting-mps'
      preLoaderRoute: typeof AdminSittingMpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proposals': {
      id: '/admin/proposals'
      path: '/proposals'
      fullPath: '/admin/proposals'
      preLoaderRoute: typeof AdminProposalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parties': {
      id: '/admin/parties'
      path: '/parties'
      fullPath: '/admin/parties'
      preLoaderRoute: typeof AdminPartiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manifesto-imports': {
      id: '/admin/manifesto-imports'
      path: '/manifesto-imports'
      fullPath: '/admin/manifesto-imports'
      preLoaderRoute: typeof AdminManifestoImportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/duplicates': {
      id: '/admin/duplicates'
      path: '/duplicates'
      fullPath: '/admin/duplicates'
      preLoaderRoute: typeof AdminDuplicatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/districts': {
      id: '/admin/districts'
      path: '/districts'
      fullPath: '/admin/districts'
      preLoaderRoute: typeof AdminDistrictsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disclaimers': {
      id: '/admin/disclaimers'
      path: '/disclaimers'
      fullPath: '/admin/disclaimers'
      preLoaderRoute: typeof AdminDisclaimersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/custom-fields': {
      id: '/admin/custom-fields'
      path: '/custom-fields'
      fullPath: '/admin/custom-fields'
      preLoaderRoute: typeof AdminCustomFieldsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community-proposals': {
      id: '/admin/community-proposals'
      path: '/community-proposals'
      fullPath: '/admin/community-proposals'
      preLoaderRoute: typeof AdminCommunityProposalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community-authors': {
      id: '/admin/community-authors'
      path: '/community-authors'
      fullPath: '/admin/community-authors'
      preLoaderRoute: typeof AdminCommunityAuthorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidate-suggestions': {
      id: '/admin/candidate-suggestions'
      path: '/candidate-suggestions'
      fullPath: '/admin/candidate-suggestions'
      preLoaderRoute: typeof AdminCandidateSuggestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assistant': {
      id: '/admin/assistant'
      path: '/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AdminAssistantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-logs': {
      id: '/admin/api-logs'
      path: '/api-logs'
      fullPath: '/admin/api-logs'
      preLoaderRoute: typeof AdminApiLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/themes': {
      id: '/$lang/themes'
      path: '/themes'
      fullPath: '/$lang/themes'
      preLoaderRoute: typeof LangThemesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/terms': {
      id: '/$lang/terms'
      path: '/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangTermsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/supporters': {
      id: '/$lang/supporters'
      path: '/supporters'
      fullPath: '/$lang/supporters'
      preLoaderRoute: typeof LangSupportersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/support': {
      id: '/$lang/support'
      path: '/support'
      fullPath: '/$lang/support'
      preLoaderRoute: typeof LangSupportRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/sitting-mps': {
      id: '/$lang/sitting-mps'
      path: '/sitting-mps'
      fullPath: '/$lang/sitting-mps'
      preLoaderRoute: typeof LangSittingMpsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/search': {
      id: '/$lang/search'
      path: '/search'
      fullPath: '/$lang/search'
      preLoaderRoute: typeof LangSearchRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/resources': {
      id: '/$lang/resources'
      path: '/resources'
      fullPath: '/$lang/resources'
      preLoaderRoute: typeof LangResourcesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/proposals': {
      id: '/$lang/proposals'
      path: '/proposals'
      fullPath: '/$lang/proposals'
      preLoaderRoute: typeof LangProposalsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/parties-compare': {
      id: '/$lang/parties-compare'
      path: '/parties-compare'
      fullPath: '/$lang/parties-compare'
      preLoaderRoute: typeof LangPartiesCompareRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/methodology': {
      id: '/$lang/methodology'
      path: '/methodology'
      fullPath: '/$lang/methodology'
      preLoaderRoute: typeof LangMethodologyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/faq': {
      id: '/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof LangFaqRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/districts': {
      id: '/$lang/districts'
      path: '/districts'
      fullPath: '/$lang/districts'
      preLoaderRoute: typeof LangDistrictsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/developers': {
      id: '/$lang/developers'
      path: '/developers'
      fullPath: '/$lang/developers'
      preLoaderRoute: typeof LangDevelopersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/data': {
      id: '/$lang/data'
      path: '/data'
      fullPath: '/$lang/data'
      preLoaderRoute: typeof LangDataRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/cookies': {
      id: '/$lang/cookies'
      path: '/cookies'
      fullPath: '/$lang/cookies'
      preLoaderRoute: typeof LangCookiesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/compare': {
      id: '/$lang/compare'
      path: '/compare'
      fullPath: '/$lang/compare'
      preLoaderRoute: typeof LangCompareRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/community-proposals': {
      id: '/$lang/community-proposals'
      path: '/community-proposals'
      fullPath: '/$lang/community-proposals'
      preLoaderRoute: typeof LangCommunityProposalsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/changelog': {
      id: '/$lang/changelog'
      path: '/changelog'
      fullPath: '/$lang/changelog'
      preLoaderRoute: typeof LangChangelogRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/ask': {
      id: '/$lang/ask'
      path: '/ask'
      fullPath: '/$lang/ask'
      preLoaderRoute: typeof LangAskRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/accessibility': {
      id: '/$lang/accessibility'
      path: '/accessibility'
      fullPath: '/$lang/accessibility'
      preLoaderRoute: typeof LangAccessibilityRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/parties/': {
      id: '/$lang/parties/'
      path: '/parties'
      fullPath: '/$lang/parties/'
      preLoaderRoute: typeof LangPartiesIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/candidates/': {
      id: '/$lang/candidates/'
      path: '/candidates'
      fullPath: '/$lang/candidates/'
      preLoaderRoute: typeof LangCandidatesIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/admin/candidates_/confirm-ec': {
      id: '/admin/candidates_/confirm-ec'
      path: '/candidates/confirm-ec'
      fullPath: '/admin/candidates/confirm-ec'
      preLoaderRoute: typeof AdminCandidatesConfirmEcRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/parties/$slug': {
      id: '/$lang/parties/$slug'
      path: '/parties/$slug'
      fullPath: '/$lang/parties/$slug'
      preLoaderRoute: typeof LangPartiesSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/my-district/$number': {
      id: '/$lang/my-district/$number'
      path: '/my-district/$number'
      fullPath: '/$lang/my-district/$number'
      preLoaderRoute: typeof LangMyDistrictNumberRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/candidates/$slug': {
      id: '/$lang/candidates/$slug'
      path: '/candidates/$slug'
      fullPath: '/$lang/candidates/$slug'
      preLoaderRoute: typeof LangCandidatesSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/public/v1/parties': {
      id: '/api/public/v1/parties'
      path: '/api/public/v1/parties'
      fullPath: '/api/public/v1/parties'
      preLoaderRoute: typeof ApiPublicV1PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/districts': {
      id: '/api/public/v1/districts'
      path: '/api/public/v1/districts'
      fullPath: '/api/public/v1/districts'
      preLoaderRoute: typeof ApiPublicV1DistrictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/catalog.jsonld': {
      id: '/api/public/v1/catalog.jsonld'
      path: '/api/public/v1/catalog.jsonld'
      fullPath: '/api/public/v1/catalog.jsonld'
      preLoaderRoute: typeof ApiPublicV1CatalogDotjsonldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/candidates': {
      id: '/api/public/v1/candidates'
      path: '/api/public/v1/candidates'
      fullPath: '/api/public/v1/candidates'
      preLoaderRoute: typeof ApiPublicV1CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-poll': {
      id: '/api/public/hooks/telegram-poll'
      path: '/api/public/hooks/telegram-poll'
      fullPath: '/api/public/hooks/telegram-poll'
      preLoaderRoute: typeof ApiPublicHooksTelegramPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-news': {
      id: '/api/public/hooks/scan-news'
      path: '/api/public/hooks/scan-news'
      fullPath: '/api/public/hooks/scan-news'
      preLoaderRoute: typeof ApiPublicHooksScanNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/manifesto-tick': {
      id: '/api/public/hooks/manifesto-tick'
      path: '/api/public/hooks/manifesto-tick'
      fullPath: '/api/public/hooks/manifesto-tick'
      preLoaderRoute: typeof ApiPublicHooksManifestoTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangAccessibilityRoute: typeof LangAccessibilityRoute
  LangAskRoute: typeof LangAskRoute
  LangChangelogRoute: typeof LangChangelogRoute
  LangCommunityProposalsRoute: typeof LangCommunityProposalsRoute
  LangCompareRoute: typeof LangCompareRoute
  LangContactRoute: typeof LangContactRoute
  LangCookiesRoute: typeof LangCookiesRoute
  LangDataRoute: typeof LangDataRoute
  LangDevelopersRoute: typeof LangDevelopersRoute
  LangDistrictsRoute: typeof LangDistrictsRoute
  LangFaqRoute: typeof LangFaqRoute
  LangMethodologyRoute: typeof LangMethodologyRoute
  LangPartiesCompareRoute: typeof LangPartiesCompareRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangProposalsRoute: typeof LangProposalsRoute
  LangResourcesRoute: typeof LangResourcesRoute
  LangSearchRoute: typeof LangSearchRoute
  LangSittingMpsRoute: typeof LangSittingMpsRoute
  LangSupportRoute: typeof LangSupportRoute
  LangSupportersRoute: typeof LangSupportersRoute
  LangTermsRoute: typeof LangTermsRoute
  LangThemesRoute: typeof LangThemesRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCandidatesSlugRoute: typeof LangCandidatesSlugRoute
  LangMyDistrictNumberRoute: typeof LangMyDistrictNumberRoute
  LangPartiesSlugRoute: typeof LangPartiesSlugRoute
  LangCandidatesIndexRoute: typeof LangCandidatesIndexRoute
  LangPartiesIndexRoute: typeof LangPartiesIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangAccessibilityRoute: LangAccessibilityRoute,
  LangAskRoute: LangAskRoute,
  LangChangelogRoute: LangChangelogRoute,
  LangCommunityProposalsRoute: LangCommunityProposalsRoute,
  LangCompareRoute: LangCompareRoute,
  LangContactRoute: LangContactRoute,
  LangCookiesRoute: LangCookiesRoute,
  LangDataRoute: LangDataRoute,
  LangDevelopersRoute: LangDevelopersRoute,
  LangDistrictsRoute: LangDistrictsRoute,
  LangFaqRoute: LangFaqRoute,
  LangMethodologyRoute: LangMethodologyRoute,
  LangPartiesCompareRoute: LangPartiesCompareRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangProposalsRoute: LangProposalsRoute,
  LangResourcesRoute: LangResourcesRoute,
  LangSearchRoute: LangSearchRoute,
  LangSittingMpsRoute: LangSittingMpsRoute,
  LangSupportRoute: LangSupportRoute,
  LangSupportersRoute: LangSupportersRoute,
  LangTermsRoute: LangTermsRoute,
  LangThemesRoute: LangThemesRoute,
  LangIndexRoute: LangIndexRoute,
  LangCandidatesSlugRoute: LangCandidatesSlugRoute,
  LangMyDistrictNumberRoute: LangMyDistrictNumberRoute,
  LangPartiesSlugRoute: LangPartiesSlugRoute,
  LangCandidatesIndexRoute: LangCandidatesIndexRoute,
  LangPartiesIndexRoute: LangPartiesIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminRouteChildren {
  AdminApiLogsRoute: typeof AdminApiLogsRoute
  AdminAssistantRoute: typeof AdminAssistantRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCandidateSuggestionsRoute: typeof AdminCandidateSuggestionsRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommunityAuthorsRoute: typeof AdminCommunityAuthorsRoute
  AdminCommunityProposalsRoute: typeof AdminCommunityProposalsRoute
  AdminCustomFieldsRoute: typeof AdminCustomFieldsRoute
  AdminDisclaimersRoute: typeof AdminDisclaimersRoute
  AdminDistrictsRoute: typeof AdminDistrictsRoute
  AdminDuplicatesRoute: typeof AdminDuplicatesRoute
  AdminManifestoImportsRoute: typeof AdminManifestoImportsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPartiesRoute: typeof AdminPartiesRoute
  AdminProposalsRoute: typeof AdminProposalsRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSittingMpsRoute: typeof AdminSittingMpsRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminVotingFaqsRoute: typeof AdminVotingFaqsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCandidatesConfirmEcRoute: typeof AdminCandidatesConfirmEcRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiLogsRoute: AdminApiLogsRoute,
  AdminAssistantRoute: AdminAssistantRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCandidateSuggestionsRoute: AdminCandidateSuggestionsRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommunityAuthorsRoute: AdminCommunityAuthorsRoute,
  AdminCommunityProposalsRoute: AdminCommunityProposalsRoute,
  AdminCustomFieldsRoute: AdminCustomFieldsRoute,
  AdminDisclaimersRoute: AdminDisclaimersRoute,
  AdminDistrictsRoute: AdminDistrictsRoute,
  AdminDuplicatesRoute: AdminDuplicatesRoute,
  AdminManifestoImportsRoute: AdminManifestoImportsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPartiesRoute: AdminPartiesRoute,
  AdminProposalsRoute: AdminProposalsRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSittingMpsRoute: AdminSittingMpsRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminVotingFaqsRoute: AdminVotingFaqsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCandidatesConfirmEcRoute: AdminCandidatesConfirmEcRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthLoginRoute: AuthLoginRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicHooksManifestoTickRoute: ApiPublicHooksManifestoTickRoute,
  ApiPublicHooksScanNewsRoute: ApiPublicHooksScanNewsRoute,
  ApiPublicHooksTelegramPollRoute: ApiPublicHooksTelegramPollRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicV1CandidatesRoute: ApiPublicV1CandidatesRoute,
  ApiPublicV1CatalogDotjsonldRoute: ApiPublicV1CatalogDotjsonldRoute,
  ApiPublicV1DistrictsRoute: ApiPublicV1DistrictsRoute,
  ApiPublicV1PartiesRoute: ApiPublicV1PartiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
